# This is a basic workflow to help you get started with Actions

name: Publish manifest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

  push:
    branches: [ release/3.0.0 ]
    paths:
      - 'manifest.json'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v5

    # Azure CLI is preinstalled on GitHub-hosted Ubuntu runners
    - name: Upload manifest to Azure Blob Storage
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}
      run: |
        az storage container create --name sample-data --only-show-errors
        az storage blob upload --container-name sample-data --name manifest.json --file manifest.json --overwrite --only-show-errors
